CREATE TABLE users (
  user_uuid BINARY(16) PRIMARY KEY DEFAULT (UUID_TO_BIN(UUID())),
  email VARCHAR(254) NOT NULL UNIQUE,
  `password` VARCHAR(60) NOT NULL
);

CREATE TABLE sections (
  section_id INT AUTO_INCREMENT PRIMARY KEY,
  user_uuid BINARY(16) NOT NULL,
  label VARCHAR(50) NOT NULL,
  FOREIGN KEY (user_uuid) REFERENCES users(user_uuid) ON DELETE CASCADE
);

CREATE TABLE movements (
  movement_id INT AUTO_INCREMENT PRIMARY KEY,
  section_id INT NOT NULL,
  label VARCHAR(50) NOT NULL,
  FOREIGN KEY (section_id) REFERENCES sections(section_id) ON DELETE CASCADE
);

CREATE TABLE variations (
  variation_id INT AUTO_INCREMENT PRIMARY KEY,
  movement_id INT NOT NULL,
  label VARCHAR(50) NOT NULL DEFAULT '',
  weight FLOAT NULL,
  reps INT NOT NULL DEFAULT 0,
  `date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (movement_id) REFERENCES movements(movement_id) ON DELETE CASCADE
);