// Entries are added by hand whenever something user-visible ships. This is
// not a dump of PR titles: internal refactors, chores, and dev-tooling
// changes are left out on purpose. Newest entry first.
//
// An item is either a plain string, or { text, issues } where `issues` is
// the list of feedback-tracker issue numbers that bullet shipped from.
// ChangelogModal badges a tagged item for any signed-in user whose own
// submissions include one of those numbers. Only tag an issue number you
// can confirm (e.g. via the PR that closed it) — an untagged bullet is
// preferable to a wrong badge.

export const CHANGELOG = [
  {
    date: '2026-09-02',
    title: 'Changelog polish, sturdier feedback drafts, and fewer false sign-outs',
    items: [
      { text: 'The changelog icon no longer looks like it was generated by AI', issues: [310] },
      { text: 'The What’s New button now shows a small dot when there’s something new to read', issues: [314] },
      { text: 'The nutrition chat’s reconnect spinner always completes a full spin before finishing', issues: [311] },
      { text: 'Habit cards no longer jump taller the first time you tally a day', issues: [309] },
      { text: 'Feedback attachments now use a plus button with chat-style thumbnails instead of a file picker', issues: [308] },
      { text: 'An in-progress manual food entry is no longer lost if you navigate away before saving it', issues: [313] },
      { text: 'You’re no longer shown as signed out when the server is briefly unreachable', issues: [312] },
    ],
  },
  {
    date: '2026-08-30',
    title: 'Food search reliability, feedback screenshots, and this changelog',
    items: [
      'Food search now returns real results far more often instead of quietly falling back to a weaker source',
      { text: 'Search results that share a name are no longer listed three times over, and store-brand foods now show the brand', issues: [298] },
      { text: 'You can attach screenshots to feedback', issues: [296] },
      { text: 'Added a reconnect button to the nutrition chat for when a reply stops mid-stream', issues: [297] },
      { text: 'Added this What’s New list', issues: [295] },
      'The app loads faster on repeat visits',
    ],
  },
  {
    date: '2026-08-26',
    title: 'Nutrition chat and food search improvements',
    items: [
      { text: 'Fiber now shows on ingredient cards, with a daily fiber goal you can set', issues: [285] },
      { text: 'Food search finds more results and shows a clear error instead of failing silently', issues: [282] },
      { text: 'Ingredient cards now line up cleanly instead of shifting between one and two rows', issues: [286] },
      { text: 'Swiping through the food search dropdown no longer accidentally selects an item', issues: [284] },
    ],
  },
  {
    date: '2026-08-22',
    title: 'Body weight trends and dining menu filters',
    items: [
      { text: 'Body weight chart now shows a smoothed trend line alongside your daily entries', issues: [275] },
      { text: 'UNC dining menu lookup now supports dietary and allergen filters', issues: [276] },
    ],
  },
  {
    date: '2026-08-19',
    title: 'Nutrition tracking polish',
    items: [
      { text: 'Added a "Today" button to quickly jump back to today’s log', issues: [264] },
      { text: 'Ingredient entries now show grams alongside servings', issues: [259] },
      { text: 'Fixed dining hall menu items that showed up with blank names', issues: [265] },
      { text: 'The feedback form now shows a real error message when your message is too long', issues: [266] },
    ],
  },
  {
    date: '2026-08-18',
    title: 'UNC dining hall support in nutrition chat',
    items: [
      'You can now ask the nutrition chat assistant about UNC dining hall food',
      { text: 'Chat now recovers automatically if a response stalls partway through', issues: [252] },
      { text: 'Fixed the barcode scanner’s Cancel button not responding on some devices', issues: [251] },
    ],
  },
  {
    date: '2026-08-16',
    title: 'Custom meals and foods fixes',
    items: [
      { text: 'Custom meals and foods no longer autosave a draft unless you actually changed something', issues: [245] },
      { text: 'Custom meals now log as a single row instead of splitting into duplicates', issues: [246, 247] },
      { text: 'Fixed a layout gap left behind when a row’s delete button is hidden', issues: [241] },
    ],
  },
  {
    date: '2026-08-15',
    title: 'Branding refresh and mobile polish',
    items: [
      { text: 'Added the new Peak mountain logo and per-page browser tab titles', issues: [236] },
      'Icon buttons are now easier to tap on mobile',
      'Fixed the home-screen app icon theme color to match the dark theme',
      { text: 'Faster weight-tracking chart animation and a clearer notes modal', issues: [230, 232] },
      { text: 'Fixed calorie rounding and the default serving size for custom meals', issues: [228, 229] },
    ],
  },
  {
    date: '2026-08-11',
    title: 'Nutrition and workout fixes',
    items: [
      { text: 'Fixed macro scaling breaking permanently after clearing the grams field', issues: [219] },
      { text: 'Multi-barcode scanning and barcode-based nutrition lookups are more reliable', issues: [213, 216, 217] },
      { text: 'Fixed the notes icon and the est. 1RM chart tooltip on the Workouts tab', issues: [212, 220] },
    ],
  },
];

// #314: date of the newest entry, used to detect unread changes. CHANGELOG
// is newest-first, so this is just the first entry's date.
export const LATEST_CHANGELOG_DATE = CHANGELOG[0]?.date ?? null;
