enum SqlError {
    NULL_ERROR = "ER_BAD_NULL_ERROR",
    PARSE_ERROR = "ER_PARSE_ERROR",
    DUPLICATE_ERROR = "ER_DUP_ENTRY",
    FIELD_ERROR = "ER_BAD_FIELD_ERROR",
    WRONG_TYPE_ERROR = 'ER_WRONG_VALUE_FOR_TYPE',
    WRONG_VALUE_ERROR = 'ER_TRUNCATED_WRONG_VALUE',
    NO_REFERENCE_ERROR = 'ER_NO_REFERENCED_ROW_2',
    TOO_LONG_ERROR = 'ER_DATA_TOO_LONG',
}

export default SqlError;